#!/bin/bash
#
# scene_cache       Start up and shut down LSRD scene cache RPC service
#
# chkconfig: 345 99 01
# description: Starts user-level daemon that is used to find scenes that have
#              arrived on the Landsat cache after LPGS processing
#

# Source function library.
. /etc/init.d/functions

# Try to use machine credentials by default
RETVAL=0

USER=espa

progpath="/home/espa/espa-site/someplace/"

prog="scene_cache.py"

progargs=""

LOCKFILE=/var/lock/subsys/$prog

case "$1" in
  start)
	# Make sure the daemon is not already running.
	if status $prog > /dev/null ; then
	   exit 0
	fi

	# Start scene_cache daemon
        echo -n "Starting $prog: "
	su - $USER -c "$progpath/$prog &"
        #daemon --user=$USER $progpath/$prog &

	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $LOCKFILE
	;;
  stop)
	# Stop scene_cache daemon.
	echo -n $"Stopping $prog: "
	#killproc $prog
        ps -eaf | grep ^$USER | grep $prog | grep -v grep | awk '{print $2}' | xargs kill -9 &> /dev/null

	RETVAL=$?
	echo
	rm -f $LOCKFILE
	;;
  restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	RETVAL=2
	;;
esac

exit $RETVAL
